project:
  type: website

website:
  title: "Homework 1"
  navbar:
    left:
      - href: index.qmd
        text: Home Page
      - href: About.qmd
        text: About Me
      - href: example_analysis.qmd
        text: Analysis
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



